using MauiPdfGenerator.SourceGenerators;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using Xunit;
using Verify = MauiPdfGenerator.Tests.SourceGenerators.CSharpSourceGeneratorVerifier<MauiPdfGenerator.SourceGenerators.StyleKeyGenerator>;

namespace MauiPdfGenerator.Tests.SourceGenerators;

public class StyleKeyGeneratorTests
{
    private const string CoreLibraryMock = @"
namespace MauiPdfGenerator.Fluent.Interfaces.Builders
{
    public interface IPdfResourceBuilder
    {
        void Style<T>(string key, System.Action<T> setup);
    }
}

namespace MauiPdfGenerator.Fluent.Models
{
    public struct PdfStyleIdentifier { public PdfStyleIdentifier(string k) {} }
}
";

    [Fact]
    public async Task Should_Generate_PdfStyles_From_ResourceBuilder_Calls()
    {
        var userCode = @"
using MauiPdfGenerator.Fluent.Interfaces.Builders;

public class AppConfig
{
    public void ConfigureResources(IPdfResourceBuilder builder)
    {
        builder.Style<object>(""EncabezadoRojo"", null);
        builder.Style<object>(""NotaPie"", null);
    }
}";

        var expectedOutput = @"// <auto-generated/>
namespace MauiPdfGenerator.Styles
{
    public static partial class PdfStyles
    {
        /// <summary>Style key for 'EncabezadoRojo'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier EncabezadoRojo { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier(""EncabezadoRojo"");

        /// <summary>Style key for 'NotaPie'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier NotaPie { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier(""NotaPie"");
    }
}";

        await new Verify.Test
        {
            TestState =
            {
                Sources = { CoreLibraryMock, userCode },
                GeneratedSources =
                {
                    (typeof(StyleKeyGenerator), "PdfStyles.g.cs", SourceText.From(expectedOutput, Encoding.UTF8))
                }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task Should_Sanitize_Invalid_Characters_And_Accents()
    {
        var userCode = @"
using MauiPdfGenerator.Fluent.Interfaces.Builders;

public class AppConfig
{
    public void ConfigureResources(IPdfResourceBuilder builder)
    {
        builder.Style<object>(""Título Principal"", null);
        builder.Style<object>(""123Inicio"", null);
    }
}";
        var expectedOutput = @"// <auto-generated/>
namespace MauiPdfGenerator.Styles
{
    public static partial class PdfStyles
    {
        /// <summary>Style key for 'Título Principal'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier Titulo_Principal { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier(""Título Principal"");

        /// <summary>Style key for '123Inicio'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier _123Inicio { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfStyleIdentifier(""123Inicio"");
    }
}";

        await new Verify.Test
        {
            TestState =
            {
                Sources = { CoreLibraryMock, userCode },
                GeneratedSources =
                {
                    (typeof(StyleKeyGenerator), "PdfStyles.g.cs", SourceText.From(expectedOutput, Encoding.UTF8))
                }
            }
        }.RunAsync();
    }
}
