namespace MauiPdfGenerator.Fluent.Interfaces.Layouts;

public interface IPdfLayoutChildHorizontalStackLayout : IPdfHorizontalStackLayout<IPdfLayoutChildHorizontalStackLayout>, IPdfLayoutChild<IPdfLayoutChildHorizontalStackLayout>
{
}
