using System.Text;
using Microsoft.CodeAnalysis.Text;
using Xunit;
using Verify = MauiPdfGenerator.SourceGenerators.Tests.CSharpSourceGeneratorVerifier<MauiPdfGenerator.SourceGenerators.FontAliasGenerator>;

namespace MauiPdfGenerator.SourceGenerators.Tests;

public class FontAliasGeneratorTests
{
    private const string MauiMock = @"
namespace Microsoft.Maui.Hosting
{
    public interface IFontCollection 
    { 
        void AddFont(string filename, string alias);
    }
    
    public static class FontCollectionExtensions
    {
        public static IFontCollection AddFont(this IFontCollection fonts, string filename, string alias = null) 
        {
            return fonts;
        }
    }
}

namespace MauiPdfGenerator.Fluent.Models
{
    public struct PdfFontIdentifier 
    { 
        public PdfFontIdentifier(string alias) { }
    }
}
";

    [Fact]
    public async Task Should_Generate_PdfFonts_From_AddFont_Calls()
    {
        var userCode = @"
using Microsoft.Maui.Hosting;

public static class MauiProgram
{
    public static void CreateMauiApp(IFontCollection fonts)
    {
        fonts.AddFont(""OpenSans-Regular.ttf"", ""OpenSansRegular"");
        fonts.AddFont(""Roboto-Bold.ttf"", ""RobotoBold"");
    }
}";

        var expectedOutput = @"// <auto-generated/>
// Generated by FontAliasGenerator from MauiPdfGenerator.
// DO NOT MODIFY MANUALLY.

namespace MauiPdfGenerator.Fonts
{
    /// <summary>
    /// Provides static <see cref=""global::MauiPdfGenerator.Fluent.Models.PdfFontIdentifier""/> identifiers
    /// for fonts registered in the MAUI application through calls to AddFont().
    /// These identifiers must be used when specifying fonts in the MauiPdfGenerator API.
    /// </summary>
    public static class PdfFonts
    {
        /// <summary>Identifier for the font with original alias 'OpenSansRegular'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfFontIdentifier OpenSansRegular { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfFontIdentifier(""OpenSansRegular"");

        /// <summary>Identifier for the font with original alias 'RobotoBold'.</summary>
        public static global::MauiPdfGenerator.Fluent.Models.PdfFontIdentifier RobotoBold { get; } = new global::MauiPdfGenerator.Fluent.Models.PdfFontIdentifier(""RobotoBold"");
    }
}";

        await new Verify.Test
        {
            TestState =
            {
                Sources = { MauiMock, userCode },
                GeneratedSources =
                {
                    (typeof(FontAliasGenerator), "PdfFonts.g.cs", SourceText.From(expectedOutput, Encoding.UTF8))
                }
            }
        }.RunAsync();
    }
}
