name: 🐞 Reporte de Error
description: Crea un reporte para ayudarnos a mejorar
title: "fix: "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar esto.

  - type: textarea
    id: tasks
    attributes:
      label: Plan de Implementación
      description: Lista las partes técnicas necesarias (Core, SourceGen, etc.) para resolver esto.
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Descripción del Error
      description: Explica qué pasó de forma clara y concisa.
      placeholder: Al intentar generar un PDF con imágenes grandes, la app se cierra...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para reproducir
      description: ¿Cómo podemos ver el error nosotros mismos?
      placeholder: |
        1. Iniciar la app Sample
        2. Ir a la pestaña 'Imágenes'
        3. Clic en 'Generar'
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Severidad
      options:
        - "Baja (Cosmético o menor)"
        - "Media (Funcionalidad rota pero con workaround)"
        - "Alta (Bloqueante / Crash)"
        - "Crítica (Hotfix necesario)"
    validations:
      required: false
