name: О Trabajo Interno
description: Tareas que no afectan versionado (docs, refactor, tests, CI, etc.)
title: "chore: "
labels: ["chore"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: Tipo de Trabajo
      description: Selecciona el tipo principal de tarea (determina el prefijo del commit).
      options:
        - "chore - Mantenimiento general / mixto"
        - "docs - Documentaci贸n"
        - "refactor - Refactorizaci贸n de c贸digo"
        - "test - Tests"
        - "perf - Mejoras de rendimiento"
        - "build - Sistema de build"
        - "ci - Configuraci贸n CI/CD"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: 驴Qu茅 hay que hacer?
      placeholder: Actualizar dependencias de .NET MAUI a la 煤ltima versi贸n...
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Plan de Implementaci贸n
      description: Lista de tareas t茅cnicas. Usa el tipo del dropdown como prefijo en cada commit.
      value: |
        - [ ] 
    validations:
      required: false
