name: 🧰 Mantenimiento / Deuda Técnica
description: Tareas internas, refactorización o actualizaciones
title: "[Maint]: "
labels: ["type: maintenance"]
body:
  - type: textarea
    id: description
    attributes:
      label: Tarea
      description: ¿Qué hay que hacer?
      placeholder: Actualizar dependencias de .NET MAUI a la última versión...
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Alcance
      options:
        - "Global / Monorepo"
        - "Core"
        - "Diagnostics"
        - "SourceGen"
        - "CI/CD"
