namespace MauiPdfGenerator.Fluent.Interfaces.Layouts.Grids;

public interface IPdfGridChildHorizontalStackLayout : IPdfHorizontalStackLayout<IPdfGridChildHorizontalStackLayout>, IPdfGridChildElement<IPdfGridChildHorizontalStackLayout>
{
}
